"""`scripts/nightly_pull.sh`, driven for real against throwaway git repos.

The job runs unattended on two machines that both append to
`metadata/index.jsonl` and both push to one remote, so the properties worth
pinning are the ones a bad night would break: it commits only what the run
wrote, it leaves a human's pending edit alone, it survives the other machine
landing a commit mid-ingest, and it refuses to run where it should not.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SCRIPT = _REPO_ROOT / "scripts/nightly_pull.sh"

# A stand-in for scripts/pull.py: "ingests" one source the way the real
# pipeline does — a raw file plus one appended index line. When RACE_CLONE is
# set it first makes the OTHER machine append and push, which is exactly the
# window the union merge has to survive.
_STUB = '''
import os, subprocess, sys, pathlib
name = sys.argv[1]
race = os.environ.get("RACE_CLONE")
if race:
    idx = pathlib.Path(race) / "metadata/index.jsonl"
    idx.write_text(idx.read_text() + '{"src": "other-machine"}\\n')
    if os.environ.get("RACE_DERIVED"):
        (pathlib.Path(race) / "knowledge/concept.md").write_text("regenerated by the other machine\\n")
        subprocess.run(["git", "-C", race, "add", "knowledge/concept.md"], check=True)
    subprocess.run(["git", "-C", race, "commit", "-qam", "other machine"], check=True)
    subprocess.run(["git", "-C", race, "push", "-q", "origin", "main"], check=True)
root = pathlib.Path(__file__).resolve().parents[1]
(root / "archive/raw").mkdir(parents=True, exist_ok=True)
(root / f"archive/raw/{name}.json").write_text("{}")
idx = root / "metadata/index.jsonl"
idx.write_text(idx.read_text() + '{"src": "%s"}\\n' % name)
if os.environ.get("RACE_DERIVED"):
    (root / "knowledge/concept.md").write_text("regenerated by this machine\\n")
'''


def _git(cwd: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(cwd), *args], check=True, capture_output=True, text=True
    ).stdout


def _clone(origin: Path, dest: Path) -> Path:
    subprocess.run(["git", "clone", "-q", str(origin), str(dest)], check=True)
    _git(dest, "config", "user.email", "t@example.com")
    _git(dest, "config", "user.name", "t")
    venv_bin = dest / ".venv/bin"
    venv_bin.mkdir(parents=True)
    (venv_bin / "python").symlink_to(sys.executable)
    return dest


@pytest.fixture
def machines(tmp_path: Path) -> tuple[Path, Path]:
    origin = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(origin)], check=True)
    seed = tmp_path / "seed"
    subprocess.run(["git", "init", "-q", "-b", "main", str(seed)], check=True)
    _git(seed, "config", "user.email", "t@example.com")
    _git(seed, "config", "user.name", "t")
    (seed / "scripts").mkdir()
    shutil.copy2(_SCRIPT, seed / "scripts/nightly_pull.sh")
    (seed / "scripts/pull.py").write_text(_STUB)
    (seed / "metadata").mkdir()
    (seed / "metadata/index.jsonl").write_text('{"src": "seed"}\n')
    (seed / "knowledge").mkdir()
    (seed / "knowledge/note.md").write_text("a note\n")
    (seed / "knowledge/concept.md").write_text("a derived note\n")
    (seed / ".gitignore").write_text(".venv/\n")
    shutil.copy2(_REPO_ROOT / ".gitattributes", seed / ".gitattributes")
    _git(seed, "add", "-A")
    _git(seed, "commit", "-qm", "seed")
    _git(seed, "remote", "add", "origin", str(origin))
    _git(seed, "push", "-q", "origin", "main")
    return _clone(origin, tmp_path / "a"), _clone(origin, tmp_path / "b")


def _run(clone: Path, *args: str, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["/bin/bash", str(clone / "scripts/nightly_pull.sh"), *args],
        capture_output=True, text=True, env={**os.environ, **(env or {})}, check=False,
    )


def test_commits_and_pushes_only_what_the_run_wrote(machines: tuple[Path, Path]) -> None:
    a, b = machines
    (a / "knowledge/note.md").write_text("a note\nmy unsaved thought\n")  # a human's pending edit

    result = _run(a, "granola")
    assert result.returncode == 0, result.stdout + result.stderr

    committed = _git(a, "show", "--name-only", "--format=", "HEAD").split()
    assert sorted(committed) == ["archive/raw/granola.json", "metadata/index.jsonl"]
    assert "knowledge/note.md" in _git(a, "status", "--porcelain")  # still pending, still theirs
    _git(b, "pull", "-q", "origin", "main")
    assert (b / "archive/raw/granola.json").exists()  # it reached the remote


def test_survives_the_other_machine_pushing_mid_ingest(machines: tuple[Path, Path]) -> None:
    """Both machines append to the same tail of index.jsonl. Without
    `merge=union` the retry rebase conflicts and the commit stays local."""
    a, b = machines
    result = _run(a, "claude_code", env={"RACE_CLONE": str(b)})
    assert result.returncode == 0, result.stdout + result.stderr
    assert "push rejected — rebasing once" in result.stdout

    _git(b, "pull", "-q", "origin", "main")
    lines = (b / "metadata/index.jsonl").read_text().splitlines()
    assert '{"src": "other-machine"}' in lines
    assert '{"src": "claude_code"}' in lines
    assert not any(line.startswith(("<<<<<<<", "=======", ">>>>>>>")) for line in lines)


def test_nothing_new_means_no_commit(machines: tuple[Path, Path]) -> None:
    a, _ = machines
    (a / "scripts/pull.py").write_text("")  # a connector with nothing to fetch
    before = _git(a, "rev-parse", "HEAD")
    result = _run(a, "granola")
    assert result.returncode == 0
    assert "nothing new" in result.stdout
    assert _git(a, "rev-parse", "HEAD") == before


def test_refuses_when_someone_is_mid_commit(machines: tuple[Path, Path]) -> None:
    a, _ = machines
    (a / "knowledge/note.md").write_text("staged by a human\n")
    _git(a, "add", "knowledge/note.md")
    result = _run(a, "granola")
    assert result.returncode == 1
    assert "staged changes" in result.stdout
    assert not (a / "archive/raw/granola.json").exists()  # never got as far as ingesting


def test_refuses_on_the_wrong_branch(machines: tuple[Path, Path]) -> None:
    a, _ = machines
    _git(a, "checkout", "-qb", "experiment")
    result = _run(a, "granola")
    assert result.returncode == 1
    assert "is not 'main'" in result.stdout


def test_usage_error_without_a_connector(machines: tuple[Path, Path]) -> None:
    a, _ = machines
    assert _run(a).returncode == 2


def test_a_conflict_in_regenerated_notes_takes_the_remote_side(machines: tuple[Path, Path]) -> None:
    """Found on the first live run, 2026-09-20: one new meeting committed 389
    paths, 379 of them `knowledge/concepts/*`, because every ingest
    regenerates the shared derived notes — and the other machine had
    regenerated the same ones during the seventeen-minute index build. The
    job's commit holds only ingest output, which the next run rebuilds, so on
    conflict the remote side wins and the run's own new files still land."""
    a, b = machines
    result = _run(a, "granola", env={"RACE_CLONE": str(b), "RACE_DERIVED": "1"})
    assert result.returncode == 0, result.stdout + result.stderr

    _git(b, "pull", "-q", "origin", "main")
    assert (b / "knowledge/concept.md").read_text() == "regenerated by the other machine\n"
    assert (b / "archive/raw/granola.json").exists()
    assert '{"src": "granola"}' in (b / "metadata/index.jsonl").read_text()


def test_never_auto_resolves_over_a_humans_unpushed_commit(machines: tuple[Path, Path]) -> None:
    """A rebase replays EVERY unpushed commit. Preferring the remote side is
    only safe when the job's commit is the sole one ahead — with a human's
    commit in the stack it would silently discard their side of a conflict."""
    a, b = machines
    (b / "knowledge/note.md").write_text("the other machine's version\n")
    _git(b, "commit", "-qam", "remote edit")
    _git(b, "push", "-q", "origin", "main")
    # A human commit on A that conflicts with it, made after A's last fetch and
    # never pushed. The job's opening sync must refuse rather than pick a side.
    (a / "knowledge/note.md").write_text("my version\n")
    _git(a, "commit", "-qam", "my hand edit")

    result = _run(a, "granola")
    assert result.returncode == 1
    assert "resolve by hand" in result.stdout
    assert (a / "knowledge/note.md").read_text() == "my version\n"  # untouched, rebase aborted
    assert not (a / "archive/raw/granola.json").exists()
