"""Source-grounded concept descriptions.

Each concept note gets a synthesized description — a short summary, a detailed
explanation, and key definitions — generated by the LLM from the *retrieved*
text of the concept's own sources (RAG), never from nothing.

The description lives in a dedicated **AI zone** delimited by
``<!-- AI-GENERATED-START/END -->``, which sits *below* the
``AUTO-GENERATED-END`` marker. That placement means ``concepts.py`` already
preserves it across concept rebuilds (it's part of the preserved tail) with no
changes to that module. The AI zone carries an ``ai-hash`` comment keyed on the
concept's source set + model + prompt version; regeneration is skipped when the
hash is unchanged, so a re-run with unchanged sources costs nothing (idempotent)
and generation is unattended — no human approval step.

Pure pieces (hashing, rendering, the surgical zone upsert) are unit-tested; the
retrieval + LLM glue is verified by running with a real provider.
"""
from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass
from collections.abc import Sequence

from pydantic import BaseModel, Field

from .config import VaultPaths
from .connections import _concept_displays, _concept_sources
from .knowledge import knowledge_records
from .metadata import latest_records_by_path
from .notes import _atomic_write
from .summarize import (
    _select_model,
    _select_provider,
    generate_structured,
    is_enabled,
)

_PROMPT_VERSION = "1"          # bump to invalidate every cached description
_RETRIEVE_TOP_K = 8
_MAX_TOKENS = 2048

_AI_START = "<!-- AI-GENERATED-START -->"
_AI_END = "<!-- AI-GENERATED-END -->"
_AUTO_END = "<!-- AUTO-GENERATED-END -->"
_HASH_RE = re.compile(r"<!--\s*ai-hash:\s*([0-9a-f]+)")

_DESCRIBE_SYSTEM = (
    "You are writing a concise encyclopedia-style entry about ONE concept for "
    "a personal knowledge vault. Ground every claim ONLY in the provided source "
    "excerpts from the user's own documents. Do not invent facts, names, dates, "
    "or definitions beyond what the excerpts support. If the excerpts are thin, "
    "write less rather than padding.\n\n"
    "Return:\n"
    "- short_summary: a single paragraph (<=150 words) defining the concept.\n"
    "- detailed_explanation: ~400-600 words using H2/H3 (##/###) markdown "
    "sections. Do NOT include a top-level # heading.\n"
    "- key_definitions: the most important sub-terms with one-line definitions. "
    "Omit when the concept has no meaningful sub-terms."
)


class KeyDefinition(BaseModel):
    term: str = Field(..., description="A sub-term of the concept.")
    definition: str = Field(..., description="One-line definition of the term.")


class ConceptDescription(BaseModel):
    """Structured concept description (the LLM's response schema)."""

    short_summary: str = Field(..., description="Single paragraph, <=150 words.")
    detailed_explanation: str = Field(
        ..., description="~400-600 words, H2/H3 markdown sections, no top-level heading."
    )
    key_definitions: list[KeyDefinition] = Field(
        default_factory=list, description="Key sub-terms and their definitions."
    )


@dataclass(frozen=True)
class DescribeStats:
    generated: int = 0
    skipped_uptodate: int = 0
    skipped_no_context: int = 0
    failed: int = 0             # LLM/provider call failed (distinct from no context)
    no_llm: bool = False
    no_index: bool = False


# ---------------------------------------------------------------------------
# pure functions
# ---------------------------------------------------------------------------

def source_set_hash(
    sources: Sequence[str], model: str, *, prompt_version: str = _PROMPT_VERSION
) -> str:
    """Cache key: changes when the source set, model, or prompt changes."""
    payload = "\n".join(sorted(set(sources))) + f"\n::{model}::{prompt_version}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def render_ai_zone_body(
    desc: ConceptDescription, *, source_hash: str, model: str
) -> str:
    """The inner body of the AI zone (markers added by ``upsert_ai_zone``)."""
    parts = [
        f"<!-- ai-hash: {source_hash} · model: {model} -->",
        "",
        "> _AI-generated from this concept's sources. Regenerated when they "
        "change; safe to edit your own notes below the marker._",
        "",
        "## Description",
        "",
        desc.short_summary.strip(),
        "",
        desc.detailed_explanation.strip(),
    ]
    defs = [d for d in desc.key_definitions if d.term.strip() and d.definition.strip()]
    if defs:
        parts += ["", "### Key definitions", ""]
        parts += [f"- **{d.term.strip()}** — {d.definition.strip()}" for d in defs]
    return "\n".join(parts)


def upsert_ai_zone(note_text: str, ai_body: str) -> str:
    """Insert or replace the AI zone, preserving everything else.

    Replaces an existing zone in place; otherwise inserts it right after the
    ``AUTO-GENERATED-END`` marker (above the user's hand-written notes).
    """
    block = f"{_AI_START}\n{ai_body.strip()}\n{_AI_END}"
    if _AI_START in note_text and _AI_END in note_text:
        pre = note_text[: note_text.index(_AI_START)].rstrip()
        post = note_text[note_text.index(_AI_END) + len(_AI_END):].lstrip("\n")
        return f"{pre}\n\n{block}\n\n{post}".rstrip() + "\n"
    if _AUTO_END in note_text:
        i = note_text.index(_AUTO_END) + len(_AUTO_END)
        head = note_text[:i].rstrip()
        tail = note_text[i:].lstrip("\n")
        return f"{head}\n\n{block}\n\n{tail}".rstrip() + "\n"
    return f"{note_text.rstrip()}\n\n{block}\n"


def existing_description_hash(note_text: str) -> str | None:
    """The ``ai-hash`` recorded in the note's AI zone, if any."""
    m = _HASH_RE.search(note_text)
    return m.group(1) if m else None


# ---------------------------------------------------------------------------
# retrieval + generation glue (verified by running)
# ---------------------------------------------------------------------------

def describe_model() -> str:
    provider = _select_provider()
    if provider is None:
        return ""
    return f"{provider}/{_select_model(provider)}"


def _retrieve(
    paths: VaultPaths,
    queries: list[tuple[str, set[str]]],
    *,
    top_k: int = _RETRIEVE_TOP_K,
) -> list[list[str]]:
    """Top-k chunk texts per query, RESTRICTED to that query's own sources.

    Each query is ``(name, allowed_sources)`` — top-k is taken only over
    chunks whose ``source_relative_path`` is in ``allowed_sources``, so a
    concept whose own sources produced no embeddable chunks lands empty
    (and is skipped) instead of borrowing text from unrelated documents,
    honouring the "grounded ONLY in the concept's own sources" contract.

    Returns a list aligned with ``queries`` (empty lists when the index is
    missing) — callers treat a fully-empty result as "no index".
    """
    empty: list[list[str]] = [[] for _ in queries]
    vectors_path = paths.metadata / "embeddings.npy"
    meta_path = paths.metadata / "embeddings_meta.jsonl"
    if not queries or not vectors_path.exists() or not meta_path.exists():
        return empty
    try:
        import numpy as np  # type: ignore[import-not-found]
    except ImportError:
        return empty
    from .semantic import _load_embedder

    vectors = np.load(vectors_path)
    with meta_path.open("r", encoding="utf-8") as fh:
        meta = [json.loads(ln) for ln in fh if ln.strip()]
    if len(meta) != vectors.shape[0]:
        return empty
    try:
        model, _ = _load_embedder()
    except Exception:  # noqa: BLE001
        return empty

    row_sources = [m.get("source_relative_path", "") for m in meta]
    q_vectors = np.asarray(
        model.encode([q for q, _ in queries], normalize_embeddings=True, show_progress_bar=False),
        dtype=np.float32,
    )
    scores = vectors @ q_vectors.T  # (n_chunks, n_queries)
    out: list[list[str]] = []
    for j, (_name, allowed) in enumerate(queries):
        col = scores[:, j].copy()
        # Mask out any chunk not belonging to this concept's own sources.
        mask = np.array([s not in allowed for s in row_sources], dtype=bool)
        if mask.any():
            col[mask] = -np.inf
        # How many candidates actually remain after masking.
        n_valid = int((~mask).sum())
        if n_valid == 0:
            out.append([])
            continue
        k = min(top_k, n_valid)
        idx = np.argpartition(-col, k - 1)[:k]
        idx = idx[np.argsort(-col[idx])]
        out.append([meta[int(i)]["text"] for i in idx if col[int(i)] != -np.inf])
    return out


def describe_concept(
    name: str,
    contexts: list[str],
    *,
    max_tokens: int = _MAX_TOKENS,
    logger: logging.Logger | None = None,
) -> ConceptDescription | None:
    """Generate a grounded description, or ``None`` if there's nothing to ground in."""
    ctx = [c for c in contexts if c and c.strip()]
    if not ctx:
        return None  # honest: no sources retrieved -> don't invent
    user = (
        f"Concept: {name}\n\n"
        "Source excerpts from the vault (use ONLY these):\n\n"
        + "\n\n---\n\n".join(ctx)
    )
    result = generate_structured(
        system=_DESCRIBE_SYSTEM,
        user=user,
        schema=ConceptDescription,
        max_tokens=max_tokens,
        logger=logger,
    )
    return result if isinstance(result, ConceptDescription) else None


def rebuild_descriptions(
    paths: VaultPaths,
    *,
    logger: logging.Logger,
    limit: int | None = None,
    force: bool = False,
) -> DescribeStats:
    """Generate/refresh AI descriptions for concepts whose sources changed.

    Unattended: regenerates every stale concept (no approval). ``limit`` bounds
    the number generated per run (cost control); ``force`` ignores the cache.
    """
    if not is_enabled():
        logger.warning("describe: no LLM provider configured — skipping")
        return DescribeStats(no_llm=True)

    concepts_dir = paths.knowledge / "concepts"
    if not concepts_dir.is_dir():
        return DescribeStats()

    model = describe_model()
    # Include curated knowledge notes as sources, exactly like concepts.py /
    # connections.py do — otherwise curated-only concepts never get a
    # description and mixed concepts' cache keys ignore curated sources.
    records = (
        list(latest_records_by_path(paths.metadata_index_jsonl).values())
        + knowledge_records(paths)
    )
    sources = _concept_sources(records)
    displays = _concept_displays(records)
    # Map each source path to its content hash so the cache key tracks
    # CONTENT, not just the set of paths: re-ingesting a revised document
    # (same path, new source_hash) must invalidate the descriptions grounded
    # in it. A path with no known hash (shouldn't happen) contributes "".
    hash_by_path = {r.relative_path: (r.source_hash or "") for r in records}

    todo: list[tuple[str, str]] = []
    skipped_uptodate = 0
    for slug in sorted(sources):
        note = concepts_dir / f"{slug}.md"
        if not note.exists():
            continue
        keyed = [f"{p}@{hash_by_path.get(p, '')}" for p in sources[slug]]
        want = source_set_hash(keyed, model)
        if not force and existing_description_hash(note.read_text(encoding="utf-8")) == want:
            skipped_uptodate += 1
            continue
        todo.append((slug, want))
    if limit is not None:
        todo = todo[:limit]
    if not todo:
        return DescribeStats(skipped_uptodate=skipped_uptodate)

    queries = [(displays.get(slug, slug), set(sources[slug])) for slug, _ in todo]
    contexts = _retrieve(paths, queries, top_k=_RETRIEVE_TOP_K)
    if all(not v for v in contexts):
        logger.warning("describe: no usable search index — run --rebuild-search-index")
        return DescribeStats(skipped_uptodate=skipped_uptodate, no_index=True)

    generated = 0
    skipped_no_context = 0
    failed = 0
    for (slug, want), ctx in zip(todo, contexts, strict=True):
        name = displays.get(slug, slug)
        # Empty retrieval for this concept's OWN sources -> honestly skip.
        if not any(c and c.strip() for c in ctx):
            skipped_no_context += 1
            continue
        desc = describe_concept(name, ctx, logger=logger)
        if desc is None:
            # We HAD context but generation returned nothing — an LLM/provider
            # failure, not an empty vault. Count it separately so a provider
            # outage isn't misreported as "no context".
            failed += 1
            continue
        body = render_ai_zone_body(desc, source_hash=want, model=model)
        note = concepts_dir / f"{slug}.md"
        _atomic_write(note, upsert_ai_zone(note.read_text(encoding="utf-8"), body))
        generated += 1
        logger.info("describe: generated %s (%d source(s))", slug, len(sources[slug]))
    return DescribeStats(
        generated=generated,
        skipped_uptodate=skipped_uptodate,
        skipped_no_context=skipped_no_context,
        failed=failed,
    )
