"""Dream-pass gate: deterministic prep for the LLM memory-consolidation
session.

The dream pass itself is an LLM session (``.claude/skills/dream-pass/``).
This module is everything deterministic around it:

- state: ``metadata/dream.json`` (``last_run``, ``last_commit``), advanced
  only by :func:`mark_done`, plus the ``metadata/dream.pending`` marker
  used by sweep to detect stalled runs.
- gate: has enough new information landed since the last dream?
- packet: the session's worklist, computed reproducibly from git history,
  ``metadata/index.jsonl`` and ``metadata/connections.jsonl``.

No LLM, no wall clock — callers inject ``as_of``/``now``.

Split (AUD-121) into sibling modules along the file's original section
boundaries — ``dream_git`` (the shared git subprocess helper),
``dream_gate_core`` (state + gate), ``dream_compiled`` (the compiled-truth
block), ``dream_contradictions`` (the contradiction detectors) and
``dream_packet`` (assembling and writing the packet). This module imports
and re-exports every name it used to define, public and private alike, so
every existing import of ``ingest_lib.dream`` keeps working unchanged.
"""
from __future__ import annotations

from .dream_compiled import (
    COMPILED_TRUTH_BUDGET,
    COMPILED_TRUTH_END,
    COMPILED_TRUTH_START,
    CONTRADICTION_BUDGET,
    EDIT_CAP,
    CompiledTruthCandidate,
    _compiled_truth_candidates,
    _entity_changeset,
    _entity_note_path,
    _log_bullets,
    _marker_offsets,
    _new_log_bullets,
    _render_open_relations,
    _strip_compiled_truth,
    _text_at,
    compiled_truth_span,
    marker_state,
)
from .dream_contradictions import (
    CONTRADICTION_FLAG_PREFIX,
    PROPOSAL_KIND,
    ContradictionCandidate,
    ProposalRelation,
    _BULLET_DATE_RE,
    _BULLET_LEADING_DATE_RE,
    _CLOSABLE_RELS,
    _CUE_RE,
    _DATE_RE,
    _KIND_RANK,
    _PROPOSAL_KIND,
    _RawFinding,
    _RESTATEMENT_MAX_FINDINGS,
    _RESTATEMENT_MIN_OVERLAP,
    _RESTATEMENT_WINDOW,
    _STOPWORDS,
    _TERMINATION_CUES,
    _WIKILINK_RE,
    _WORD_RE,
    _address_proposals,
    _bullet_tokens,
    _claim_text,
    _closure_relation,
    _contradictions,
    _describe_relation,
    _finding,
    _interval_conflicts,
    _is_contradiction_flag,
    _mentions_target,
    _proposal_fact,
    _relation_from_entry,
    _relation_vs_log,
    _restated_facts,
)
from .dream_gate_core import (
    GateVerdict,
    DreamState,
    _GENERATED_PATH_PREFIXES,
    _PENDING_NAME,
    _PROPOSAL_INBOX_PREFIX,
    _STATE_NAME,
    _changed_knowledge_notes,
    _commit_before,
    _is_generated_note,
    _iso_z,
    _new_sources,
    _only_compiled_truth_changed,
    _parse_ts,
    evaluate_gate,
    load_pending_since,
    load_state,
    mark_done,
    record_pending,
)
from .dream_git import GitError, _git
from .dream_packet import (
    AdjudicatedFinding,
    DreamPacket,
    EditBudget,
    PairCandidate,
    ProposalOutcome,
    _ENTITY_ROOTS,
    _active_entities,
    _as_mapping,
    _candidate_pairs,
    _existing_dream_notes,
    _parse_promote_relations,
    _require_str,
    _written_connection_stems,
    build_packet,
    parse_adjudicated,
    write_proposals,
)

# Every name this module used to define, public and private alike — kept
# bound here (and listed below) so `from ingest_lib.dream import _whatever`
# and `ingest_lib.dream._whatever` (including monkeypatching it) keep
# working exactly as before the split.
__all__ = [
    "AdjudicatedFinding",
    "COMPILED_TRUTH_BUDGET",
    "COMPILED_TRUTH_END",
    "COMPILED_TRUTH_START",
    "CONTRADICTION_BUDGET",
    "CONTRADICTION_FLAG_PREFIX",
    "CompiledTruthCandidate",
    "ContradictionCandidate",
    "DreamPacket",
    "DreamState",
    "EDIT_CAP",
    "EditBudget",
    "GateVerdict",
    "GitError",
    "PROPOSAL_KIND",
    "PairCandidate",
    "ProposalOutcome",
    "ProposalRelation",
    "_BULLET_DATE_RE",
    "_BULLET_LEADING_DATE_RE",
    "_CLOSABLE_RELS",
    "_CUE_RE",
    "_DATE_RE",
    "_ENTITY_ROOTS",
    "_GENERATED_PATH_PREFIXES",
    "_KIND_RANK",
    "_PENDING_NAME",
    "_PROPOSAL_INBOX_PREFIX",
    "_PROPOSAL_KIND",
    "_RESTATEMENT_MAX_FINDINGS",
    "_RESTATEMENT_MIN_OVERLAP",
    "_RESTATEMENT_WINDOW",
    "_RawFinding",
    "_STATE_NAME",
    "_STOPWORDS",
    "_TERMINATION_CUES",
    "_WIKILINK_RE",
    "_WORD_RE",
    "_active_entities",
    "_address_proposals",
    "_as_mapping",
    "_bullet_tokens",
    "_candidate_pairs",
    "_changed_knowledge_notes",
    "_claim_text",
    "_closure_relation",
    "_commit_before",
    "_compiled_truth_candidates",
    "_contradictions",
    "_describe_relation",
    "_entity_changeset",
    "_entity_note_path",
    "_existing_dream_notes",
    "_finding",
    "_git",
    "_interval_conflicts",
    "_is_contradiction_flag",
    "_is_generated_note",
    "_iso_z",
    "_log_bullets",
    "_marker_offsets",
    "_mentions_target",
    "_new_log_bullets",
    "_new_sources",
    "_only_compiled_truth_changed",
    "_parse_promote_relations",
    "_parse_ts",
    "_proposal_fact",
    "_relation_from_entry",
    "_relation_vs_log",
    "_render_open_relations",
    "_require_str",
    "_restated_facts",
    "_strip_compiled_truth",
    "_text_at",
    "_written_connection_stems",
    "build_packet",
    "compiled_truth_span",
    "evaluate_gate",
    "load_pending_since",
    "load_state",
    "mark_done",
    "marker_state",
    "parse_adjudicated",
    "record_pending",
    "write_proposals",
]
